# Generated by Django 5.2.14 on 2026-05-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an external image URL (used when no file is uploaded)', verbose_name='Image URL'),
        ),
    ]
